### ISSUE TITLE
Some documentation could do with a quick update

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunkit-magex#35]
https://docs.sunpy.org/projects/sunkit-magex/en/latest/performance.html this still references "FORTRAN" in a few places.

**Comment by STBadman** [comment]
So this doc references `sunkit-magex.pfss.tracing.FortranTracer` which still exists. My understanding is if you have streamtracer <v1.2.0 then using this class will use Fortran, but otherwise FotranTracer in fact uses RUST - is that true?

If so (if the version affects the tracing backend language) - then should we rename the class PerfomanceTracer or something similar? or if Fortran support is going away entirely, rename it RustTracer ?

**Comment by jgieseler** [comment]
> So this doc references `sunkit-magex.pfss.tracing.FortranTracer` which still exists. My understanding is if you have streamtracer <v1.2.0 then using this class will use Fortran, but otherwise FotranTracer in fact uses RUST - is that true?

That's also my understanding.

> If so (if the version affects the tracing backend language) - then should we rename the class PerfomanceTracer or something similar? or if Fortran support is going away entirely, rename it RustTracer ?

That's why I added "Automatically pick working/best Tracer" #37 :sweat_smile: But yeah, I think the idea is to get rid of Fortran totally, and then I would give it a generic name.

**Comment by Cadair** [comment]
The references to fortran outside of the link to the class should at least be removed. This issue was also more general about just giving the docs a quick read through to make sure they are up to date.

**Comment by samaloney** [comment]
I guess the example gallery directory `using_pfsspy` should be renamed to `using_sunkit_magex`?
